name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Unzip folder
        run: |
           tar -xf files\Folder.zip -C files
           del files\Folder.zip
           dir files
        
      - name: Install WiX
        run: dotnet tool install --global wix
        
      - name: Build WiX on Windows
        shell: bash
        run: |
          APP_VERSION=4.12.14 wix build app.wxs
        
      - name: Add generated binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-MSI
          path: App.msi
          if-no-files-found: error

